from __future__ import annotations

FK = "FK"
READS_TABLE = "READS_TABLE"
WRITES_TABLE = "WRITES_TABLE"
CALLS = "CALLS"
INCLUDES = "INCLUDES"
ASSOCIATION = "ASSOCIATION"
COMPOSITION = "COMPOSITION"
MASTER_TX = "MASTER_TX"
CROSS_PACKAGE = "CROSS_PACKAGE"

ALL_RELATIONS = frozenset(
    {FK, READS_TABLE, WRITES_TABLE, CALLS, INCLUDES, ASSOCIATION, COMPOSITION, MASTER_TX, CROSS_PACKAGE}
)
