from __future__ import annotations

FK = "FK"
READS_TABLE = "READS_TABLE"
WRITES_TABLE = "WRITES_TABLE"
CALLS = "CALLS"
INCLUDES = "INCLUDES"
ASSOCIATION = "ASSOCIATION"
COMPOSITION = "COMPOSITION"
MASTER_TX = "MASTER_TX"
CROSS_PACKAGE = "CROSS_PACKAGE"
ODATA_ENTITY_SET = "ODATA_ENTITY_SET"
ODATA_ACTION = "ODATA_ACTION"
NAV_PROP = "NAV_PROP"

ALL_RELATIONS = frozenset(
    {
        FK, READS_TABLE, WRITES_TABLE, CALLS, INCLUDES, ASSOCIATION, COMPOSITION,
        MASTER_TX, CROSS_PACKAGE, ODATA_ENTITY_SET, ODATA_ACTION, NAV_PROP,
    }
)
