from __future__ import annotations

from enum import Enum


class SapObjectKind(str, Enum):
    PROGRAM = "PROGRAM"
    FUNCTION_MODULE = "FUNCTION_MODULE"
    CDS_VIEW = "CDS_VIEW"
    TABLE = "TABLE"
    DATA_ELEMENT = "DATA_ELEMENT"
    DOMAIN = "DOMAIN"
    BAPI = "BAPI"
    IDOC = "IDOC"
    ODATA_ENTITY = "ODATA_ENTITY"
    ODATA_ENTITY_SET = "ODATA_ENTITY_SET"
    ODATA_ACTION = "ODATA_ACTION"
    ODATA_FUNCTION = "ODATA_FUNCTION"
    ODATA_SERVICE = "ODATA_SERVICE"
    TRANSPORT_OBJECT = "TRANSPORT_OBJECT"
    RFC_METADATA = "RFC_METADATA"
    HANA_CALCULATION_VIEW = "HANA_CALCULATION_VIEW"
    BW_OBJECT = "BW_OBJECT"
    DATASPHERE_OBJECT = "DATASPHERE_OBJECT"
    UNKNOWN = "UNKNOWN"
